---
- name: Assert Debian Buster
  assert:
    that: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'

- name: Validate database names
  assert:
    that:
      - engine_api_db_confd_name == engine_api_db_auth_name
  when:
    - engine_api_db_confd_name is defined
    - engine_api_db_auth_name is defined

- name: Assert UTF-8 locale
  shell: grep 'LANG=.*\.UTF-8"\?$' /etc/default/locale
