---
- name: Install APT python bindings and GPG
  apt:
    name:
      - python-apt
      - gpg
    state: present

- name: Add Wazo distribution key
  apt_key:
    url: http://mirror.wazo.community/wazo_current.key
    id: 2769B67EDBFF423F6874D7663F1BF7FC527FBC6A
    state: present

- name: Gather packages facts
  package_facts:
    manager: apt

- name: Add bootstrap Wazo repository
  apt_repository:
    repo: deb http://mirror.wazo.community/debian {{ wazo_distribution }} {{ wazo_debian_repo }}
    state: present
    filename: wazo-install
    update_cache: yes
  when: '"wazo-dist" not in ansible_facts.packages'

- name: Install wazo-dist
  apt:
    name: wazo-dist
    state: latest

- name: Add persistent Wazo repository
  command: wazo-dist --{{ wazo_debian_repo }}-repo {{ wazo_distribution }}

- name: Remove bootstrap Wazo repository
  apt_repository:
    repo: deb http://mirror.wazo.community/debian {{ wazo_distribution }} {{ wazo_debian_repo }}
    state: absent
    filename: wazo-install
    update_cache: yes
  when: '"wazo-dist" not in ansible_facts.packages'
