- name: Assert Debian Stretch
  assert:
    that: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'
- name: Create certificate dir
  file:
    path: /etc/nestbox/https
    state: directory
- name: Copy certificate generation config
  copy:
    src: files/openssl-x509.cfg
    dest: /tmp/openssl-x509.cfg
    owner: root
    group: root
    mode: 0644
- name: Generate a self signed OpenSSL certificate
  command: >-
    openssl req
    -x509 -sha256 -nodes
    -days 3650
    -newkey rsa:2048
    -config /tmp/openssl-x509.cfg
    -keyout {{ https_private_key }}
    -out {{ https_certificate }}
  args:
    creates: /etc/nestbox/https/public-certificate.pem
- name: Create group for certificate
  group:
    name: nestbox-certs
- name: Set permissions for certificate
  file:
    path: "{{ item }}"
    group: nestbox-certs
    mode: o=rw,g=r
  loop:
    - "{{ https_private_key }}"
    - "{{ https_certificate }}"

- name: Install nginx
  apt:
    name: nginx
    state: present
- name: Disable the default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx
- name: Install nginx site for nestbox
  template:
    src: templates/nginx-site
    dest: /etc/nginx/sites-available/nestbox
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
- name: Enable nginx site for nestbox
  file:
    path: /etc/nginx/sites-enabled/nestbox
    src: ../sites-available/nestbox
    state: link
  notify:
    - reload nginx

- name: Install RabbitMQ
  apt:
    name: rabbitmq-server
    state: present

- name: Install HTTPS driver for APT
  apt:
    name: apt-transport-https
    state: latest
- name: Add Nestbox APT PGP key
  apt_key:
    url: http://mirror.wazo.community/wazo_current.key
    id: 2769B67EDBFF423F6874D7663F1BF7FC527FBC6A
    state: present

- name: Configure client certificate for APT
  template:
    src: templates/apt-client-certs-config
    dest: /etc/apt/apt.conf.d/nestbox-mirror-{{ nestbox_mirror_user}}
- name: Create directory for client cert
  file:
    dest: /etc/apt/certs
    state: directory
- name: Copy client certificate
  copy:
    src: /tmp/mirror_keys/{{ item }}
    dest: /etc/apt/certs/{{ item }}
    owner: _apt
    mode: 0400
  loop:
    - "{{ nestbox_mirror_user }}.key"
    - "{{ nestbox_mirror_user }}.crt"

- name: Add Nestbox Debian repository
  apt_repository:
    repo: deb https://mirror.wazo.io/nestbox nestbox main
    state: present
    update_cache: yes

- name: Preconfigure wazo-auth package
  debconf:
    name: wazo-auth
    question: "{{ item }}"
    vtype: boolean
    value: true
  loop:
    - wazo-auth/bootstrap-skip
    - wazo-auth/db-skip
- name: Create wazo-auth config dir
  file:
    path: /etc/wazo-auth/conf.d
    state: directory
- name: Add wazo-auth config
  template:
    src: templates/wazo-auth.yml
    dest: /etc/wazo-auth/conf.d/50-nestbox.yml
    owner: root
    group: root
    mode: 0644
  notify: restart wazo-auth
- name: Install wazo-auth
  apt:
    name: wazo-auth
    state: present
  notify: reload nginx
- name: Add wazo-auth user in groups
  user:
    name: wazo-auth
    groups:
      - nestbox-certs
  notify: restart wazo-auth
- name: Remove wazo-auth default config
  file:
    path: "/etc/wazo-auth/conf.d/{{ item }}"
    state: absent
  with_items:
    - 050-xivo-consul-config.yml
    - 050-xivo-consul-token.yml
  notify: restart wazo-auth

- name: Preconfigure wazo-deployd package
  debconf:
    name: wazo-deployd
    question: wazo-deployd/db-skip
    vtype: boolean
    value: true
- name: Create wazo-deployd config dir
  file:
    path: /etc/wazo-deployd/conf.d
    state: directory
    owner: root
    mode: 755
- name: Copy wazo-deployd config
  template:
    src: templates/wazo-deployd.yml
    dest: /etc/wazo-deployd/conf.d/50-nestbox.yml
- name: Install wazo-deployd
  apt:
    name: wazo-deployd
    state: present
- name: Add wazo-deployd user in groups
  user:
    name: wazo-deployd
    groups:
      - nestbox-certs
  notify: restart wazo-deployd

- name: Preconfigure nestbox-confd package
  debconf:
    name: nestbox-confd
    question: nestbox-confd/db-skip
    vtype: boolean
    value: true
- name: Install nestbox-confd
  apt:
    name: nestbox-confd
    state: present
  notify: reload nginx
- name: Initialize nestbox-confd bus queues
  command: nestbox-confd-init-amqp

- name: Install nestbox-ui
  apt:
    name: nestbox-ui
    state: present
  notify: reload nginx

- name: Install nestbox-ui-wazo-plugins
  apt:
    name: nestbox-ui-wazo-plugins
    state: present
  notify: restart nestbox-ui
