---
- hosts: edge-proxy
  become: yes
  roles:
    - role: debian-nexsis-repo
    - role: mwolff44.kamailio-mw
      vars:
        kamailio_manage_repo: False
        kamailio_version: 51
        kamailio_install_conf: true
        kamailio_packages:
          - kamailio
          - kamailio-tls-modules
          - kamailio-extra-modules
          - kamailio-postgres-modules
          - kamailio-outbound-modules
          - kamailio-systemd-modules
          - kamailio-utils-modules
          - kamailio-xml-modules
          - kamailio-websocket-modules
        kamailio_create_db: false # does the script create the kamailio DB (the engine must be installed before)
        kamailio_db_engine: 'PGSQL' # check Kamailio doc for supported DB engine (PGSQL)

    - role: edge-proxy
      vars:
        kamailio_app: 'EDP'
