- hosts: mirror.wazo.io
  remote_user: root
  tasks:
    - name: Ensure variable for user name is defined
      assert:
        that: 'private_repo_user is defined'
        msg: "You must define the variable `private_repo_user` to copy the SSH key. Use `--extra-vars private_repo_user=user`."
    - name: Ensure variable for user name is valid
      assert:
        that: 'private_repo_user != "ca"'
        msg: "Invalid value for variable private_repo_user: '{{ private_repo_user }}'"
    - name: Generate private key
      openssl_privatekey:
        path: /etc/nginx/client_certs/nestbox/{{ private_repo_user }}.key
        state: present
    - name: Generate CSR
      openssl_csr:
        path: /etc/nginx/client_certs/nestbox/{{ private_repo_user }}.csr
        privatekey_path: /etc/nginx/client_certs/nestbox/{{ private_repo_user }}.key
        state: present
        common_name: "{{ private_repo_user }}.clients.wazo.io"
    - name: Generate certificate signed by CA
      command: |
        openssl x509
        -req
        -days 3650
        -sha256
        -in {{ private_repo_user }}.csr
        -CA ca.crt
        -CAkey ca.key
        -CAcreateserial
        -out {{ private_repo_user }}.crt
      args:
        chdir: "/etc/nginx/client_certs/nestbox"
        creates: "{{ private_repo_user }}.crt"
    - name: Copy client certificate from mirror
      fetch:
        src: /etc/nginx/client_certs/nestbox/{{ private_repo_user }}.crt
        dest: "{{ nestbox_repo_client_cert }}"
        flat: yes
    - name: Copy client key from mirror
      fetch:
        src: /etc/nginx/client_certs/nestbox/{{ private_repo_user }}.key
        dest: "{{ nestbox_repo_client_key }}"
        flat: yes
