- hosts: database
  pre_tasks:
    - name: Change PostgreSQL port
      become: yes
      include_role:
        name: geerlingguy.postgresql
      vars:
        postgresql_global_config_options:
          - option: port
            value: "{{ db_port }}"
        postgresql_users: []
  roles:
    - role: geerlingguy.postgresql
      become: yes
      vars:
        postgresql_hba_entries:
          - { type: local, database: all, user: postgres, auth_method: peer }
          - { type: local, database: all, user: all, auth_method: peer }
          - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
          - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
          - { type: host, database: all, user: all, address: all, auth_method: md5 }
        postgresql_global_config_options:
          - option: port
            value: "{{ db_port }}"
          - option: listen_addresses
            value: "*"
        postgresql_users:
          - name: postgres
            password: superpass
            port: "{{ db_port }}"
