- hosts: reverse-proxy
  roles:
    - role: reverse-proxy-certificates
    - role: geerlingguy.nginx
      vars:
        nginx_vhosts:
          - state: present
            listen: "443 ssl"
            server_name: "rpx01"
            root: "/var/www/html"
            extra_parameters: |
              location ^~ /nestbox/ {
                proxy_pass https://{{ nestbox_host }}:{{ nestbox_port }}/;

                proxy_set_header    Host                $http_host;
                proxy_set_header    X-Script-Name       /nestbox;
                proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
              }
              location ^~ /api/ {
                proxy_pass https://{{ engine_api_host }}:{{ engine_api_port }}/api/;

                proxy_set_header    Host                $http_host;
                proxy_set_header    X-Script-Name       /api;
                proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
              }
              location ^~ /api/websocketd/ {
                proxy_pass https://{{ engine_api_host }}:{{ engine_api_port }}/api/websocketd/;
                  proxy_http_version 1.1;
                  proxy_read_timeout 90s;

                  proxy_set_header    Upgrade         $http_upgrade;
                  proxy_set_header    Connection      "upgrade";
                  proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
              }
              location = /api/asterisk/ws {
                if ($http_sec_websocket_protocol != 'sip') {
                    return 403;
                }

                proxy_pass https://{{ b2bua_host }}:{{ b2bua_port_https }}/ws;
                proxy_http_version 1.1;
                proxy_read_timeout 1d;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
              }
              ssl_certificate     /etc/nginx/certs/reverse-proxy.pem;
              ssl_certificate_key /etc/nginx/certs/reverse-proxy.key;
