---
- import_playbook: postgresql.yml

- hosts: b2bua
  become: yes
  roles:
    - role: b2bua

- hosts: engine-api
  become: yes
  roles:
    - role: engine-api
    - role: engine-api-init

- hosts: engine-api
  tasks:
    - name: Install wazo-service
      apt:
        name: wazo-service
        state: latest
    - name: Install remaining daemons
      apt:
        name:
          - consul
          - xivo-dxtora
          - wazo-call-logd
          - wazo-dird
          - wazo-plugind
          - wazo-webhookd
          - xivo-agentd
          - xivo-ctid
          - xivo-dird-phoned
          - xivo-dxtora
        state: latest
