---
- hosts: all
  become: yes
  roles:
    - role: preflight_checks

- hosts:
    - database
    - b2bua
    - engine-api
  become: yes
  roles:
    - role: debian_upgrade_first

- import_playbook: postgresql.yml

- hosts: b2bua
  become: yes
  roles:
    - role: b2bua

- hosts: engine-api
  become: yes
  roles:
    - role: engine-api
    - role: uc-engine
    - role: engine-api-init

- hosts: uc-ui
  become: yes
  roles:
    - role: uc-ui
