- name: Assert debian Stretch
  assert:
    that: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'

- name: Add Wazo distribution key
  apt_key:
    url: http://mirror.wazo.community/xivo_current.key
    state: present

- name: Add bootstrap Wazo repository
  apt_repository:
    repo: deb http://mirror.wazo.community/debian phoenix-stretch main
    state: present
    filename: wazo-install
    update_cache: yes

- name: Install rtpengine packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ rtpe_packages }}"

- name: Copy config file
  template:
    src: "{{ rtpe_config_tempate_dir }}/{{ item }}.j2"
    dest: "{{ rtpe_conf_dir }}/{{ item }}"
    backup: yes
  with_items: "{{ rtpe_config_files }}"
  notify: restart rtpengine
  when: rtpe_install_conf

- name: Restart VM
  // To Do
