- name: Assert debian Stretch
  assert:
    that: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'

- name: Install rtpengine packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ rtpe_packages }}"

- name: Copy config file
  template:
    src: "{{ rtpe_config_tempate_dir }}/{{ item }}.j2"
    dest: "{{ rtpe_config_dir }}/{{ item }}"
    backup: yes
  with_items: "{{ rtpe_config_files }}"
  notify: restart rtpengine
  when: rtpe_install_conf

- name: Enable rtpengine
  systemd:
    name: ngcp-rtpengine-daemon
    enabled: yes

- name: Allow rtpengine to run
  shell: sed -i 's/RUN_RTPENGINE=no/RUN_RTPENGINE=yes/' /etc/default/ngcp-rtpengine-daemon

- name: Create file log
  file:
    path: /var/log/rtpengine
    state: touch

