- name: Assert Debian Stretch
  assert:
    that: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'

- name: Copy wazo-auth database preconfiguration
  template:
    src: templates/wazo-auth.cfg.j2
    dest: /tmp/wazo-auth.cfg
- name: Reconfigure database options for wazo-auth package
  command: debconf-set-selections /tmp/wazo-auth.cfg
- name: Initialize wazo-auth database
  command: dpkg-reconfigure wazo-auth --frontend noninteractive

- name: Copy wazo-router-confd database preconfiguration
  template:
    src: templates/wazo-router-confd.cfg.j2
    dest: /tmp/wazo-router-confd.cfg
- name: Reconfigure database options for wazo-router-confd package
  command: debconf-set-selections /tmp/wazo-router-confd.cfg
- name: Initialize wazo-router-confd database
  command: dpkg-reconfigure wazo-router-confd --frontend noninteractive

- name: Initialize wazo-auth, wazo-router-confd
  script: "files/router-init.sh
           '{{ router_root_user }}'
           '{{ router_root_password }}'"
