---
- name: Install wazo-service
  apt:
    name: wazo-service
    state: latest
- name: Install wazo-upgrade
  apt:
    name: xivo-upgrade
    state: latest
- name: Install xivo-base
  apt:
    name: xivo-base
    state: latest
- name: Install wazo-setupd
  apt:
    name: wazo-setupd
    state: latest
- name: Install nestbox plugin
  apt:
    name:
      - wazo-deployd-client
      - wazo-nestbox-plugin
    state: latest
  notify: restart wazo-setupd
- name: Change Wazo distribution for later upgrades
  command: wazo-dist --{{ wazo_debian_repo_upgrade }}-repo {{ wazo_distribution_upgrade }}
