---
- name: Install wazo-service
  apt:
    name: wazo-service
    state: latest
- name: Install wazo-upgrade
  apt:
    name: xivo-upgrade
    state: latest
- name: Install remaining daemons
  apt:
    name:
      - consul
      - xivo-dxtora
      - xivo-monitoring
      - wazo-call-logd
      - wazo-dird
      - wazo-plugind
      - wazo-webhookd
      - xivo-agentd
      - xivo-ctid
      - xivo-dird-phoned
      - xivo-dxtora
    state: latest

- name: Install nestbox plugin
  apt:
    name:
      - wazo-deployd-client
      - wazo-nestbox-plugin
    state: latest
