- import_tasks: kamailio.yml
  tags:
  - kamailio

- import_tasks: wazo-db.yml
  tags:
  - wazo-db

- import_tasks: wazo-packages.yml
  tags:
  - wazo-packages

- name: Create/Configure SSL certs
  include_role:
    name: wazo-certs

- name: Install Wazo auth
  include_role:
    name: wazo-auth

- name : Wait for wazo-auth is available
  wait_for:
    port: 9497
    delay: 10

- name: Create a tenant
  command: "wazo-auth-cli tenant create main"

- name: Create API client
  command: "wazo-auth-cli user create {{ api_client_name }} --tenant main --password {{ api_client_password }} --purpose external_api"

- name: Create policy
  command: "wazo-auth-cli policy create api-client-policy --tenant main --acl 'auth.admin.#'"

- name: Add policy to user
  command: "wazo-auth-cli user add {{ api_client_name }} --policy wazo_default_admin_policy"

- name: Enable policy for API client
  command: "wazo-auth-cli user add {{ api_client_name }} --policy api-client-policy"
