- import_tasks: kamailio.yml
  tags:
  - kamailio

- import_tasks: wazo-db.yml
  tags:
  - wazo-db

- import_tasks: wazo-packages.yml
  tags:
  - wazo-packages

- name: Create/Configure SSL certs
  include_role:
    name: wazo-certs

- name: Install Wazo auth
  include_role:
    name: wazo-auth
