- import_tasks: kamailio.yml
  tags:
  - kamailio

- import_tasks: wazo-db.yml
  tags:
  - wazo-db

- import_tasks: wazo-packages.yml
  tags:
  - wazo-packages

- name: Create/Configure SSL certs
  include_role:
    name: wazo-certs

- name: Install Wazo auth
  include_role:
    name: wazo-auth

- name: Create tenant
  command: "wazo-auth-cli tenant create {{ tenant_name }}"

- name: Create API client
  command: "wazo-auth-cli user create {{ api_client_name }} --tenant {{ tenant_name }} --password {{ api_client_password }} --purpose external_api"

- name: Create policy
  command: "wazo-auth-cli policy create api-client-policy --tenant {{ tenant_name }} --acl 'confd.#'"

- name: Enable policy for API client
  command: "wazo-auth-cli user add {{ api_client_name }} --policy api-client-policy"
  when: engine_api_configure_wizard == "true"
