- name: Assert Debian Stretch
  assert:
    that: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'

- name: Install wazo-auth-cli
  apt:
    name: wazo-auth-cli
    state: present

- name: Copy wazo-auth database preconfiguration
  template:
    src: templates/wazo-auth.cfg.j2
    dest: /tmp/wazo-auth.cfg
- name: Reconfigure database options for wazo-auth package
  command: debconf-set-selections /tmp/wazo-auth.cfg
- name: Initialize wazo-auth database
  command: dpkg-reconfigure wazo-auth -f noninteractive

- name: Copy nestbox-confd database preconfiguration
  template:
    src: templates/nestbox-confd.cfg.j2
    dest: /tmp/nestbox-confd.cfg
- name: Reconfigure database options for nestbox-confd package
  command: debconf-set-selections /tmp/nestbox-confd.cfg
- name: Initialize nestbox-confd database
  command: dpkg-reconfigure nestbox-confd -f noninteractive

- name: Copy wazo-deployd database preconfiguration
  template:
    src: templates/wazo-deployd.cfg.j2
    dest: /tmp/wazo-deployd.cfg
- name: Reconfigure database options for wazo-deployd package
  command: debconf-set-selections /tmp/wazo-deployd.cfg
- name: Initialize wazo-deployd database
  command: dpkg-reconfigure wazo-deployd -f noninteractive

- name: Initialize wazo-auth, nestbox-confd
  script: "files/nestbox-init.sh {{ nestbox_db_host }} {{ nestbox_db_port }} {{ nestbox_db_confd_user }} {{ nestbox_db_confd_password }} {{ nestbox_db_confd_name }} {{ nestbox_root_user }} {{ nestbox_root_password }}"
  args:
    creates: /etc/nestbox-ui/conf.d/50-default-policies.yml
