- name: reload nginx
  debug: msg="checking config first"
  changed_when: True
  notify:
    - check nginx configuration
    - reload nginx - after config check
- name: check nginx configuration
  command: "nginx -t"
  register: result
  changed_when: "result.rc != 0"
  check_mode: no

- name: reload nginx - after config check
  service:
    name: nginx
    state: reloaded

- name: restart wazo-auth
  service:
    name: wazo-auth
    state: restarted

- name: restart wazo-router-confd
  service:
    name: wazo-router-confd
    state: restarted
