---
- name: Copy wazo-auth database preconfiguration
  template:
    src: templates/wazo-auth.cfg.j2
    dest: /tmp/wazo-auth.cfg

- name: Reconfigure database options for wazo-auth package
  command: debconf-set-selections /tmp/wazo-auth.cfg

- name: Initialize wazo-auth database
  command: dpkg-reconfigure wazo-auth --frontend noninteractive

- name: Install wazo-auth-keys
  apt:
    name: wazo-auth-keys
    state: latest

- name: Create service users with wazo-auth-keys
  command: wazo-auth-keys service update

- name: Copy main database preconfiguration
  template:
    src: templates/xivo-manage-db.cfg.j2
    dest: /tmp/xivo-manage-db.cfg

- name: Apply main database preconfiguration
  command: debconf-set-selections /tmp/xivo-manage-db.cfg

- name: Initialize main database
  command: dpkg-reconfigure xivo-manage-db --frontend noninteractive

- name: Fix Twisted dropin.cache
  command: twistd --help-reactors

- name: Start Wazo services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - wazo-agid
    - xivo-amid
    - wazo-confd
    - xivo-confgend
    - wazo-calld
    - wazo-provd
    - wazo-websocketd

- name: Create an index.html for the home page
  become: true
  file:
    src: /var/www/html/index.wazo.html
    dest: /var/www/html/index.html
    state: link
  when: groups['uc-ui'] is not defined
