- name: Assert Debian Stretch
  assert:
    that: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'

- name: Copy wazo-auth database preconfiguration
  template:
    src: templates/wazo-auth.cfg
    dest: /tmp/wazo-auth.cfg
- name: Reconfigure database options for wazo-auth package
  command: debconf-set-selections /tmp/wazo-auth.cfg
- name: Initialize wazo-auth database
  command: dpkg-reconfigure wazo-auth -f noninteractive

- name: Copy main database preconfiguration
  template:
    src: templates/xivo-manage-db.cfg
    dest: /tmp/xivo-manage-db.cfg
- name: Apply main database preconfiguration
  command: debconf-set-selections /tmp/xivo-manage-db.cfg
- name: Initialize main database
  command: dpkg-reconfigure xivo-manage-db -f noninteractive

- name: Start Wazo services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - xivo-agid
    - xivo-amid
    - xivo-confd
    - xivo-confgend
    - xivo-ctid-ng
    - xivo-provd

- name: Install xivo-confd-client-python3
  apt:
    name: xivo-confd-client-python3
    state: present
- name: Pass wizard
  script: "files/wizard.py --entity-name {{ entity_name }} --language {{ language }} --number-start {{ number_start }} --number-end {{ number_end }} --password {{ engine_root_password }}"
  args:
    executable: python3
    creates: /var/lib/xivo/configured
