---
- name: Install Wazo auth
  include_role:
    name: wazo_auth

- name: Create an index.html for the home page
  become: true
  file:
    src: /var/www/html/index.wazo.html
    dest: /var/www/html/index.html
    state: link
  when: groups['uc-ui'] is not defined
