- name: Add the apt key for kamailio official repository
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: fb40d3e6508ea4c8

- name: Add the kamailio official apt repository
  apt_repository:
    repo: deb http://deb.kamailio.org/kamailio52 buster main
    state: present
    update_cache: yes

- name: Install the kamailio packages
  apt:
    name:
      - kamailio
      - kamailio-json-modules
      - kamailio-utils-modules
      - kamailio-extra-modules
      - kamailio-xml-modules
      - wazo-kamailio-config
    state: present

- name: Install kamailio-local
  template:
    src: templates/kamailio-local.cfg.j2
    dest: /etc/kamailio/kamailio-local.cfg
