---
- name: Install Kamailio
  vars:
    kamailio_interface: "{{ router_interface }}"
    kamailio_advertise_address: "{%if router_advertise_address is defined %}{{ router_advertise_address }}{% endif %}"
    kamailio_advertise_port: "{% if router_advertise_port is defined %}{{ router_advertise_port }}{% endif %}"
    kamailio_routing_api_endpoint: "{{ router_api_endpoint_confd }}/kamailio/routing"
    kamailio_cdr_api_endpoint: "{{ router_api_endpoint_confd }}/kamailio/cdr"
    kamailio_rtpengine_list: "{{ router_rtpengine_list }}"
  include_role:
    name: wazo_kamailio
