- import_tasks: wazo-packages.yml
  tags:
  - wazo-packages

- import_tasks: kamailio.yml
  tags:
  - kamailio

- import_tasks: rabbitmq.yml
  tags:
  - rabbitmq

- import_tasks: wazo-db.yml
  tags:
  - wazo-db
