---
- name: Assert Debian Stretch
  assert:
    that: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'

- name: Create certificate dir
  file:
    path: /etc/wazo-router/https
    state: directory
- name: Create group for certificate
  group:
    name: wazo-router-certs
- name: Install custom certificate for HTTPS
  copy:
    src: "{{ router_https_cert }}"
    dest: /etc/wazo-router/https/public-certificate.pem
    owner: root
    group: wazo-router-certs
    mode: o=rw,g=r
  notify:
    - restart wazo-auth
    - restart wazo-router-confd
    - reload nginx
- name: Install custom private key for HTTPS
  copy:
    src: "{{ router_https_private_key }}"
    dest: /etc/wazo-router/https/private-key.pem
    owner: root
    group: wazo-router-certs
    mode: o=rw,g=r
  notify:
    - restart wazo-auth
    - restart wazo-router-confd
    - reload nginx

- name: Install nginx
  apt:
    name: nginx
    state: latest
- name: Disable the default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx
- name: Install nginx site for wazo-router
  template:
    src: templates/nginx-site.j2
    dest: /etc/nginx/sites-available/wazo-router
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
- name: Enable nginx site for wazo-router
  file:
    path: /etc/nginx/sites-enabled/wazo-router
    src: ../sites-available/wazo-router
    state: link
  notify:
    - reload nginx

- name: Add Wazo distribution key
  apt_key:
    url: http://mirror.wazo.community/wazo_current.key
    id: 2769B67EDBFF423F6874D7663F1BF7FC527FBC6A
    state: present
- name: Add wazo-router repository
  apt_repository:
    repo: deb http://mirror.wazo.community/wazo-router wazo-router main
    state: present
    filename: wazo-router
    update_cache: yes

- name: Preconfigure wazo-auth package
  debconf:
    name: wazo-auth
    question: "{{ item }}"
    vtype: boolean
    value: true
  loop:
    - wazo-auth/bootstrap-skip
    - wazo-auth/db-skip
- name: Create wazo-auth config dir
  file:
    path: /etc/wazo-auth/conf.d
    state: directory
- name: Add wazo-auth config
  template:
    src: templates/wazo-auth.yml.j2
    dest: /etc/wazo-auth/conf.d/50-wazo-router.yml
    owner: root
    group: root
    mode: 0644
  notify: restart wazo-auth
- name: Install wazo-auth
  apt:
    name: wazo-auth
    state: present
  notify: reload nginx
- name: Add wazo-auth user in groups
  user:
    name: wazo-auth
    groups:
      - wazo-router-certs
  notify: restart wazo-auth
- name: Remove wazo-auth default config
  file:
    path: "/etc/wazo-auth/conf.d/{{ item }}"
    state: absent
  with_items:
    - 050-xivo-consul-config.yml
    - 050-xivo-consul-token.yml
  notify: restart wazo-auth

- name: Preconfigure wazo-router-confd package
  debconf:
    name: wazo-router-confd
    question: wazo-router-confd/db-skip
    vtype: boolean
    value: true
- name: Create wazo-router-confd config dir
  file:
    path: /etc/wazo-router-confd/conf.d
    state: directory
    owner: root
    mode: 755
- name: Copy wazo-router-confd config
  template:
    src: templates/wazo-router-confd.yml.j2
    dest: /etc/wazo-router-confd/conf.d/50-router.yml
  notify: restart wazo-router-confd
- name: Install wazo-router-confd
  apt:
    name: wazo-router-confd
    state: present
- name: Add wazo-router-confd user in groups
  user:
    name: wazo-router-confd
    groups:
      - wazo-router-certs
  notify: restart wazo-router-confd
