---
- name: Install wazo-router-confd
  apt:
    name: wazo-router-confd
    state: latest

- name: Create /etc/wazo
  file:
    path: /etc/wazo
    state: directory

- name: Install wazo-router-confd.ini
  template:
    src: templates/wazo-router-confd.ini.j2
    dest: /etc/wazo/wazo-router-confd.ini
  notify:
    - restart wazo-router-confd
