---
- hosts: all
  tasks:
    - name: Run the installation script # noqa 301
      become: yes
      command: "ansible-playbook -i inventories/c4-aio c4-aio.yml -vv"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Check packages # noqa 301 303
      become: yes
      command: "apt-get install -fs -qq"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Check Kamailio config # noqa 301
      become: yes
      command: "kamailio -c -f /etc/kamailio/kamailio.cfg"

    - name: Check Kamailio status # noqa 301 303
      become: yes
      command: "systemctl status kamailio"

    - name: Check RTPEngine status # noqa 301 303
      become: yes
      command: "systemctl status ngcp-rtpengine-daemon"
