---
- hosts: all
  tasks:
    - name: Create docker images # noqa 301
      command: "make -k"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Launch docker-compose to test docker images # noqa 301
      command: "docker-compose up -d"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Get Consul services # noqa 301
      command: "docker-compose exec -T consul_server consul catalog services"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      register: result
      until: result.rc == 0
      retries: 6
      delay: 10

    - name: Check that RabbitMQ is listed in Consul services # noqa 301
      shell: |
        set -o pipefail
        docker-compose exec -T consul_server consul catalog services|grep rabbitmq
      args:
        chdir: "{{ zuul.project.src_dir }}"
        executable: /bin/bash
      register: result
      until: result.rc == 0
      retries: 6
      delay: 10
