---
- hosts: all
  tasks:
    - name: Create docker images
      shell: "for f in $(ls -d roles/*/docker); do ./bin/role2docker $(basename $(dirname $f)); done"
      args:
        chdir: "{{ zuul.project.src_dir }}"
