---
- hosts: all
  tasks:
    - name: Activate uc-ui in inventory
      become: yes
      blockinfile:
        path: "{{ zuul.project.src_dir }}/inventories/uc-engine"
        marker: "# Uncomment the 2 following lines if you want to deploy wazo-ui too:"
        block: |
          [uc-ui:children]
          uc-engine-host

    - name: Run the installation script
      become: yes
      command: "ansible-playbook -i inventories/uc-engine uc-engine.yml -vv --extra-vars engine_api_configure_wizard=true --extra-vars engine_api_root_password=secret"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Check packages
      become: yes
      command: "apt-get install -fs -qq"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Check services
      become: yes
      shell: "wazo-service status"

    - name: Run simple validation tests
      become: yes
      command: "ansible-playbook -i inventories/uc-engine test.yml"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Get service facts
      become: yes
      service_facts:

    - name: Assert wazo-ui is running
      assert:
        that: ansible_facts.services['wazo-ui.service'].state == 'running'

    - name: Reset engine
      become: yes
      shell: "wazo-reset -f"

    - name: create acceptance config
      blockinfile:
        create: yes
        path: ~/.wazo-acceptance/config.yml
        block: |
          debug:
            global: True

            acceptance: True
            linphone: True
          instances:
            default:
              wazo_host: 127.0.0.1

    - name: Setup acceptance tests
      shell: "tox -e setup"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-acceptance"

    - name: Run acceptance tests
      shell: "tox -e behave -- features/daily"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-acceptance"

