- name: Install mitmproxy
  apt:
    name: mitmproxy
    state: present

- name: Change nginx listening port
  lineinfile:
    path: /etc/nginx/sites-enabled/wazo
    regexp: '^    listen [0-9]+ default_server;'
    line: '    listen 8443 default_server;'
    firstmatch: yes
  notify:
    - restart nginx

- name: Change nginx IPv6 listening port
  lineinfile:
    path: /etc/nginx/sites-enabled/wazo
    regexp: '^    listen \[::\]:[0-9]+ default_server;'
    line: '    listen [::]:8443 default_server;'
    firstmatch: yes
  notify:
    - restart nginx

- tags:
    - never
    - uninstall
  block:
  - name: Restore nginx listening port
    lineinfile:
      path: /etc/nginx/sites-enabled/wazo
      regexp: '^    listen [0-9]+ default_server;'
      line: '    listen 443 default_server;'
      firstmatch: yes
    notify:
      - restart nginx

  - name: Restore nginx IPv6 listening port
    lineinfile:
      path: /etc/nginx/sites-enabled/wazo
      regexp: '^    listen \[::\]:[0-9]+ default_server;'
      line: '    listen [::]:443 default_server;'
      firstmatch: yes
    notify:
      - restart nginx

- name: Install mitmdump service file
  template:
    src: templates/mitmdump.service.j2
    dest: /etc/systemd/system/mitmdump.service
  notify:
    - reload systemd

- name: Run mitmdump
  service:
    name: mitmdump
    state: started

- name: Remove mitmdump
  tags:
    - never
    - uninstall
  block:
    - name: Stop mitmdump service
      service:
        name: mitmdump
        state: stopped
      ignore_errors: yes
    - name: Uninstall mitmdump service file
      file:
        path: /etc/systemd/system/mitmdump.service
        state: absent
      notify:
        - reload systemd

- name: Find wazo service config directories
  find:
    paths: /etc
    patterns:
      - 'wazo-*'
      - 'xivo-*'
    recurse: no
    file_type: directory
  register: wazo_config_directories

- name: Find wazo service config directories
  find:
    paths: "{{ wazo_config_directories.files | map(attribute='path') | list }}"
    patterns: 'conf.d'
    recurse: no
    file_type: directory
  register: wazo_config_custom_directories

- name: Create temporary mitm config directory
  tempfile:
    prefix: wazo-mitm-config
    state: directory
  register: wazo_mitm_config_master_directory

- name: Copy mitm redirection config file
  template:
    src: templates/mitm-wazo-agentd.yml.j2
    dest: '{{ wazo_mitm_config_master_directory.path }}/mitm-{{ item }}.yml'
  loop: '{{ redirected_wazo_services }}'

# Using template module is way too slow to duplicate that many files
- name: Replicate mitm redirection config file to all services
  shell: |
    for wazo_config_custom_directory in {{ ' '.join(wazo_config_custom_directories.files | map(attribute='path') | list) }} ; do
      cp -t $wazo_config_custom_directory {{ wazo_mitm_config_master_directory.path }}/mitm-{{ item }}.yml
    done
  loop: '{{ redirected_wazo_services }}'
  notify:
    - restart wazo services

- name: Remove temporary mitm config directory
  file:
    path: '{{ wazo_mitm_config_master_directory.path }}'
    state: absent

- tags:
    - uninstall
    - never
  block:
    - name: Find mitmdump config files
      find:
        paths: /etc/
        patterns: 'mitm-*.yml'
        recurse: yes
      register: mitmdump_wazo_config_files
    # Using file module is way too slow to remove that many files
    - name: Remove mitmdump config files
      shell: "rm -f {{ ' '.join(mitmdump_wazo_config_files.files | map(attribute='path') | list) }}"
      notify:
        - restart wazo services
      warn: false
